Implement Memory Monitoring
1p4pk/SusML pull request #9
Opened 2020-06-25 09:56 UTC by raminqaf

2020-06-25 14:25 UTC, 1p4pk commented on src/malware_prediction/main_eval.py
>  ROWS = DataLoader(MalwareDataset.load(TEST_ENCODED_CSV_PATH, is_train=False), batch_size=1).dataset.rows
Das sollte hier auch noch über die Eingabe gesteuert werden...

2020-06-25 14:25 UTC, 1p4pk commented on src/malware_prediction/preprocessor.py
> -
Kannst reverten hier :D

2020-06-25 15:57 UTC, 1p4pk requested changes
Drei Sachen sind kommentiert

2020-06-25 15:57 UTC, 1p4pk commented on src/malware_prediction/main_model.py
> +        return optim.AdamW(parameters, lr=0.001)
Hat das einen Grund warum lr bei den jeweiligen Adams anders ist?

2020-06-26 07:41 UTC, raminqaf commented on src/malware_prediction/main_model.py
> +        return optim.AdamW(parameters, lr=0.001)
das war das default Nummer von Pytorch docs

2020-06-26 07:45 UTC, raminqaf commented on src/malware_prediction/main_model.py
> +        return optim.AdamW(parameters, lr=0.001)
@1p4pk was meinst du dazu?

2020-07-23 14:14 UTC, 1p4pk approved these changes

2020-07-23 14:19 UTC, merged